name: Defect
description: Report Boat Defect
title: "Boat: Defect Description"
labels: ["defect", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this damage report!
  - type: input
    id: boat
    attributes:
      label: Boat
      description: Boat number or name
      placeholder: e.g. U68
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: whats-broken
    attributes:
      label: What is broken?
      description: What part of the boat is broken?
      placeholder: What is broken?
    validations:
      required: true
  - type: checkboxes
    id: state
    attributes:
      label: In what state is the boat now?
      description:
      options:
        - label: Usable
        - label: Not usable
        - label: Missing
  - type: textarea
    id: other
    attributes:
      label: Other
      description: Anything else you would like to add?
      placeholder: Anything else?
  - type: markdown
    attributes:
      value: |
        If possible also select the appropriate **label** in the right-hand column.
